{
 "title": "Project Pipeline Chunk Metrics Dashboard",
 "description": "Extractor monitoring dashboard ",
 "time": { "from": "2025-05-24T17:19:11.663Z", "to": "2025-06-01T17:19:11.663Z" },
 "panels": [
  {
   "title": "Data Write Failures",
   "type": "barchart",
   "description": "Data Write Failures",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "project": "hygiene-prediction-434",
     "rawSql": "SELECT\r\n  CAST(offset AS STRING) AS offset_label,\r\n  IF(gcs_write_skipped, 1, 0) AS gcs_failure_flag\r\nFROM\r\n  `hygiene-prediction-434.PipelineMonitoring.chunk_metrics`\r\nORDER BY\r\n  offset ASC\r\n"
    }
   ]
  },
  {
   "title": "API Failures",
   "type": "barchart",
   "description": "API failure results in no download for an offset",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "project": "hygiene-prediction-434",
     "rawSql": "SELECT\r\n  CAST(offset AS STRING) AS offset_label,\r\n  IF(fetch_skipped, 1, 0) AS fetch_skipped_flag\r\nFROM\r\n  `hygiene-prediction-434.PipelineMonitoring.chunk_metrics`\r\nORDER BY\r\n  offset ASC\r\n"
    }
   ]
  },
  {
   "title": "Rows Loaded and Dropped per Chunk",
   "type": "barchart",
   "description": "Rows loaded and dropped per 1000 row chunk during data exporting",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "project": "hygiene-prediction-434",
     "rawSql": "SELECT\r\n  timestamp,\r\n  rows_extracted,\r\n  rows_dropped\r\nFROM\r\n  `hygiene-prediction-434.PipelineMonitoring.chunk_metrics`\r\nORDER BY\r\n  timestamp ASC\r\n\r\n\r\n"
    }
   ]
  },
  {
   "title": "Number of Seconds per 1000 Rows",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "project": "hygiene-prediction-434",
     "rawSql": "SELECT\r\n  CAST(offset AS STRING) AS offset_label,\r\n  chunk_duration_seconds\r\nFROM\r\n  `hygiene-prediction-434.PipelineMonitoring.chunk_metrics`\r\nORDER BY\r\n  offset ASC\r\n"
    }
   ]
  }
 ]
}